--[[
=====================================================================
 FishData.lua - everything that can be fished up (starter data)
=====================================================================
 Source: your fishing CSV. 681 items. The CSV was laid out sideways
 (one item per column) with four rows: ID, Name, Type, Required Fishing.

 Fields: id = item ID, name, type = the item type from your CSV,
         skill = fishing skill needed to catch it (left out when "-").

 The CSV has no zones. Zones are filled in by YOUR catches in game: every
 fishing catch is logged against the zone you caught it in (Capture.lua), and
 the Fishing Log shows an item under a zone once you have caught it there.
 In "All zones" every item below is listed, greyed out until caught.

 FUTURE: if you later have items per zone, add  zones = {["Durotar"] = true}
 to a row. The Fishing Log will then show that item greyed out in that zone
 and can count "caught / total" for the zone.

 Items you catch that are NOT in this list still appear in the Fishing Log,
 under "Not in your list", so you can send them to be added.

 SECTIONS (how the Fishing Log groups items) are set at the bottom of this
 file. Move a single item with ns.FISH_ITEM_SECTION, change a whole type with
 ns.FISH_SECTION_OF, or add a name rule to ns.FISH_NAME_RULES. Section names listed in
 ns.FISH_SECTION_ORDER appear in that order.
=====================================================================
]]

local ADDON, ns = ...

ns.FishList = {
  {id=118, name="Minor Healing Potion", type="Potion", skill=1},
  {id=727, name="Notched Shortsword", type="One-Handed Sword", skill=5},
  {id=766, name="Flanged Mace", type="One-Handed Mace", skill=2},
  {id=768, name="Lumberjack Axe", type="One-Handed Axe", skill=4},
  {id=770, name="Pointy Crocolisk Tooth", type="Junk"},
  {id=774, name="Malachite", type="Trade Good"},
  {id=789, name="Stout Battlehammer", type="One-Handed Mace", skill=17},
  {id=804, name="Large Blue Sack", type="Bag"},
  {id=805, name="Small Red Pouch", type="Bag"},
  {id=818, name="Tigerseye", type="Trade Good"},
  {id=828, name="Small Blue Pouch", type="Bag"},
  {id=856, name="Blue Leather Bag", type="Bag"},
  {id=857, name="Large Red Sack", type="Bag"},
  {id=858, name="Lesser Healing Potion", type="Potion", skill=3},
  {id=865, name="Leaden Mace", type="One-Handed Mace", skill=26},
  {id=866, name="Monk's Staff", type="Staff", skill=37},
  {id=929, name="Healing Potion", type="Potion", skill=12},
  {id=954, name="Scroll of Strength", type="Scroll", skill=10},
  {id=955, name="Scroll of Intellect", type="Scroll", skill=5},
  {id=1180, name="Scroll of Stamina", type="Scroll", skill=5},
  {id=1206, name="Moss Agate", type="Trade Good"},
  {id=1210, name="Shadowgem", type="Trade Good"},
  {id=1438, name="Warrior's Shield", type="Shield", skill=4},
  {id=1467, name="Spotted Sunfish", type="Quest"},
  {id=1478, name="Scroll of Protection II", type="Scroll", skill=15},
  {id=1529, name="Jade", type="Trade Good", skill=30},
  {id=1608, name="Skullcrusher Mace", type="One-Handed Mace", skill=42},
  {id=1639, name="Grinning Axe", type="Two-Handed Axe", skill=44},
  {id=1640, name="Monstrous War Axe", type="Two-Handed Axe", skill=37},
  {id=1705, name="Lesser Moonstone", type="Trade Good"},
  {id=1710, name="Greater Healing Potion", type="Potion", skill=21},
  {id=1712, name="Scroll of Spirit II", type="Scroll", skill=15},
  {id=1725, name="Large Knapsack", type="Bag"},
  {id=1994, name="Ebonclaw Reaver", type="One-Handed Axe", skill=41},
  {id=2073, name="Dwarven Hatchet", type="One-Handed Axe", skill=10},
  {id=2075, name="Priest's Mace", type="One-Handed Mace", skill=7},
  {id=2078, name="Northern Shortsword", type="One-Handed Sword", skill=13},
  {id=2079, name="Sergeant's Warhammer", type="One-Handed Mace", skill=12},
  {id=2140, name="Carving Knife", type="Dagger", skill=6},
  {id=2318, name="Light Leather", type="Leather"},
  {id=2319, name="Medium Leather", type="Leather"},
  {id=2406, name="Pattern: Fine Leather Boots", type="Leatherworking Pattern"},
  {id=2407, name="Pattern: White Leather Jerkin", type="Leatherworking Pattern"},
  {id=2409, name="Pattern: Dark Leather Tunic", type="Leatherworking Pattern"},
  {id=2447, name="Peacebloom", type="Herb"},
  {id=2455, name="Minor Mana Potion", type="Potion", skill=5},
  {id=2553, name="Recipe: Elixir of Minor Agility", type="Alchemy Recipe"},
  {id=2555, name="Recipe: Swiftness Potion", type="Alchemy Recipe"},
  {id=2598, name="Pattern: Red Linen Robe", type="Tailoring Pattern"},
  {id=2601, name="Pattern: Gray Woolen Robe", type="Tailoring Pattern"},
  {id=2632, name="Curved Dagger", type="Dagger", skill=9},
  {id=2657, name="Red Leather Bag", type="Bag"},
  {id=2819, name="Cross Dagger", type="Dagger", skill=23},
  {id=2881, name="Plans: Runed Copper Breastplate", type="Blacksmithing Plans"},
  {id=2882, name="Plans: Silvered Bronze Shoulders", type="Blacksmithing Plans"},
  {id=2883, name="Plans: Deadly Bronze Poniard", type="Blacksmithing Plans"},
  {id=2958, name="Journeyman's Pants", type="Cloth Armor", skill=5},
  {id=2959, name="Journeyman's Boots", type="Cloth Armor", skill=4},
  {id=2960, name="Journeyman's Gloves", type="Cloth Armor", skill=4},
  {id=2961, name="Burnt Leather Vest", type="Leather Armor", skill=6},
  {id=2962, name="Burnt Leather Breeches", type="Leather Armor", skill=5},
  {id=2963, name="Burnt Leather Boots", type="Leather Armor", skill=4},
  {id=2964, name="Burnt Leather Gloves", type="Leather Armor", skill=5},
  {id=2965, name="Warrior's Tunic", type="Mail Armor", skill=6},
  {id=2966, name="Warrior's Pants", type="Mail Armor", skill=5},
  {id=2968, name="Warrior's Gloves", type="Mail Armor", skill=4},
  {id=2970, name="Spellbinder Pants", type="Cloth Armor", skill=11},
  {id=2971, name="Spellbinder Boots", type="Cloth Armor", skill=9},
  {id=2972, name="Spellbinder Gloves", type="Cloth Armor", skill=9},
  {id=2973, name="Hunting Tunic", type="Leather Armor", skill=12},
  {id=2974, name="Hunting Pants", type="Leather Armor", skill=11},
  {id=2975, name="Hunting Boots", type="Leather Armor", skill=9},
  {id=2976, name="Hunting Gloves", type="Leather Armor", skill=10},
  {id=2977, name="Veteran Armor", type="Mail Armor", skill=11},
  {id=2979, name="Veteran Boots", type="Mail Armor", skill=9},
  {id=2982, name="Seer's Pants", type="Cloth Armor", skill=15},
  {id=2983, name="Seer's Boots", type="Cloth Armor", skill=12},
  {id=2985, name="Inscribed Leather Breastplate", type="Leather Armor", skill=16},
  {id=2987, name="Inscribed Leather Boots", type="Leather Armor", skill=13},
  {id=2988, name="Inscribed Leather Gloves", type="Leather Armor", skill=14},
  {id=2992, name="Burnished Gloves", type="Mail Armor", skill=15},
  {id=2997, name="Bolt of Woolen Cloth", type="Cloth"},
  {id=3012, name="Scroll of Agility", type="Scroll", skill=10},
  {id=3013, name="Scroll of Protection", type="Scroll", skill=1},
  {id=3036, name="Heavy Shortbow", type="Bow", skill=10},
  {id=3037, name="Whipwood Recurve Bow", type="Bow", skill=29},
  {id=3039, name="Short Ash Bow", type="Bow", skill=18},
  {id=3040, name="Hunter's Muzzle Loader", type="Gun", skill=14},
  {id=3042, name="BKP \"Sparrow\" Smallbore", type="Gun", skill=28},
  {id=3055, name="Forest Leather Chestpiece", type="Leather Armor", skill=21},
  {id=3057, name="Forest Leather Boots", type="Leather Armor", skill=19},
  {id=3065, name="Bright Boots", type="Cloth Armor", skill=18},
  {id=3067, name="Bright Pants", type="Cloth Armor", skill=21},
  {id=3184, name="Hook Dagger", type="Dagger", skill=15},
  {id=3187, name="Sacrificial Kris", type="Dagger", skill=39},
  {id=3190, name="Beatstick", type="Two-Handed Mace", skill=3},
  {id=3192, name="Short Bastard Sword", type="Two-Handed Sword", skill=7},
  {id=3193, name="Oak Mallet", type="Two-Handed Mace", skill=16},
  {id=3195, name="Barbaric Battle Axe", type="Two-Handed Axe", skill=13},
  {id=3200, name="Burnt Leather Bracers", type="Leather Armor", skill=3},
  {id=3201, name="Barbarian War Axe", type="Two-Handed Axe", skill=23},
  {id=3205, name="Inscribed Leather Bracers", type="Leather Armor", skill=12},
  {id=3206, name="Cavalier Two-hander", type="Two-Handed Sword", skill=23},
  {id=3207, name="Hunting Bracers", type="Leather Armor", skill=9},
  {id=3208, name="Conk Hammer", type="Two-Handed Mace", skill=43},
  {id=3210, name="Brutal War Axe", type="Two-Handed Axe", skill=25},
  {id=3213, name="Veteran Bracers", type="Mail Armor", skill=8},
  {id=3214, name="Warrior's Bracers", type="Mail Armor", skill=4},
  {id=3385, name="Lesser Mana Potion", type="Potion", skill=14},
  {id=3395, name="Recipe: Limited Invulnerability Potion", type="Alchemy Recipe"},
  {id=3396, name="Recipe: Elixir of Lesser Agility", type="Alchemy Recipe"},
  {id=3430, name="Sniper Rifle", type="Gun", skill=39},
  {id=3609, name="Plans: Copper Chain Vest", type="Blacksmithing Plans"},
  {id=3610, name="Plans: Gemmed Copper Gauntlets", type="Blacksmithing Plans"},
  {id=3612, name="Plans: Green Iron Gauntlets", type="Blacksmithing Plans"},
  {id=3641, name="Journeyman's Bracers", type="Cloth Armor", skill=3},
  {id=3643, name="Spellbinder Bracers", type="Cloth Armor", skill=9},
  {id=3647, name="Bright Bracers", type="Cloth Armor", skill=18},
  {id=3740, name="Decapitating Sword", type="One-Handed Sword", skill=19},
  {id=3820, name="Stranglekelp", type="Herb"},
  {id=3827, name="Mana Potion", type="Potion", skill=22},
  {id=3832, name="Recipe: Elixir of Detect Lesser Invisibility", type="Alchemy Recipe"},
  {id=3857, name="Coal", type="Metal & Stone"},
  {id=3864, name="Citrine", type="Trade Good"},
  {id=3866, name="Plans: Jade Serpentblade", type="Blacksmithing Plans"},
  {id=3867, name="Plans: Golden Iron Destroyer", type="Blacksmithing Plans"},
  {id=3869, name="Plans: Shadow Crescent Axe", type="Blacksmithing Plans"},
  {id=3914, name="Journeyman's Backpack", type="Bag"},
  {id=3928, name="Superior Healing Potion", type="Potion", skill=35},
  {id=4037, name="Silver-thread Pants", type="Cloth Armor", skill=25},
  {id=4041, name="Aurora Cowl", type="Cloth Armor", skill=34},
  {id=4049, name="Emblazoned Bracers", type="Leather Armor", skill=23},
  {id=4059, name="Glyphed Bracers", type="Leather Armor", skill=32},
  {id=4062, name="Imperial Leather Pants", type="Leather Armor", skill=40},
  {id=4064, name="Emblazoned Buckler", type="Shield", skill=25},
  {id=4071, name="Glimmering Mail Breastplate", type="Mail Armor", skill=26},
  {id=4072, name="Glimmering Mail Gauntlets", type="Mail Armor", skill=25},
  {id=4076, name="Mail Combat Boots", type="Mail Armor", skill=30},
  {id=4089, name="Ricochet Blunderbuss", type="Gun", skill=43},
  {id=4294, name="Pattern: Hillman's Belt", type="Leatherworking Pattern"},
  {id=4299, name="Pattern: Guardian Armor", type="Leatherworking Pattern"},
  {id=4304, name="Thick Leather", type="Leather", skill=32},
  {id=4305, name="Bolt of Silk Cloth", type="Cloth"},
  {id=4339, name="Bolt of Mageweave", type="Cloth"},
  {id=4345, name="Pattern: Red Woolen Boots", type="Tailoring Pattern"},
  {id=4346, name="Pattern: Heavy Woolen Cloak", type="Tailoring Pattern"},
  {id=4349, name="Pattern: Phoenix Pants", type="Tailoring Pattern"},
  {id=4350, name="Pattern: Spider Silk Slippers", type="Tailoring Pattern"},
  {id=4352, name="Pattern: Boots of the Enchanter", type="Tailoring Pattern"},
  {id=4363, name="Copper Modulator", type="Part"},
  {id=4364, name="Coarse Blasting Powder", type="Part"},
  {id=4371, name="Bronze Tube", type="Part"},
  {id=4377, name="Heavy Blasting Powder", type="Part"},
  {id=4382, name="Bronze Framework", type="Part"},
  {id=4408, name="Schematic: Mechanical Squirrel", type="Engineering Schematic"},
  {id=4409, name="Schematic: Small Seaforium Charge", type="Engineering Schematic"},
  {id=4410, name="Schematic: Shadow Goggles", type="Engineering Schematic"},
  {id=4496, name="Small Brown Pouch", type="Bag"},
  {id=4500, name="Traveler's Backpack", type="Bag"},
  {id=4560, name="Fine Scimitar", type="One-Handed Sword", skill=1},
  {id=4562, name="Severing Axe", type="Two-Handed Axe", skill=5},
  {id=4563, name="Billy Club", type="One-Handed Mace", skill=4},
  {id=4564, name="Spiked Club", type="Two-Handed Mace", skill=8},
  {id=4565, name="Simple Dagger", type="Dagger", skill=1},
  {id=4566, name="Sturdy Quarterstaff", type="Staff", skill=8},
  {id=4567, name="Merc Sword", type="Two-Handed Sword", skill=11},
  {id=4568, name="Grunt Axe", type="One-Handed Axe", skill=16},
  {id=4569, name="Staunch Hammer", type="One-Handed Mace", skill=9},
  {id=4570, name="Birchwood Maul", type="Two-Handed Mace", skill=10},
  {id=4571, name="War Knife", type="Dagger", skill=12},
  {id=4575, name="Medicine Staff", type="Staff", skill=14},
  {id=4603, name="Raw Spotted Yellowtail", type="Meat", skill=35},
  {id=4658, name="Warrior's Cloak", type="Cloak", skill=3},
  {id=4659, name="Warrior's Girdle", type="Mail Armor", skill=3},
  {id=4662, name="Journeyman's Cloak", type="Cloak", skill=3},
  {id=4663, name="Journeyman's Belt", type="Cloth Armor", skill=4},
  {id=4665, name="Burnt Cloak", type="Cloak", skill=3},
  {id=4666, name="Burnt Leather Belt", type="Leather Armor", skill=4},
  {id=4677, name="Veteran Cloak", type="Cloak", skill=7},
  {id=4678, name="Veteran Girdle", type="Mail Armor", skill=9},
  {id=4684, name="Spellbinder Belt", type="Cloth Armor", skill=8},
  {id=4690, name="Hunting Belt", type="Leather Armor", skill=8},
  {id=4695, name="Burnished Cloak", type="Cloak", skill=13},
  {id=4697, name="Burnished Girdle", type="Mail Armor", skill=15},
  {id=4698, name="Seer's Mantle", type="Cloth Armor", skill=16},
  {id=4699, name="Seer's Belt", type="Cloth Armor", skill=13},
  {id=4700, name="Inscribed Leather Spaulders", type="Leather Armor", skill=16},
  {id=4706, name="Lambent Scale Cloak", type="Cloak", skill=19},
  {id=4709, name="Forest Leather Mantle", type="Leather Armor", skill=20},
  {id=4711, name="Glimmering Cloak", type="Cloak", skill=23},
  {id=4712, name="Glimmering Mail Girdle", type="Mail Armor", skill=24},
  {id=4713, name="Silver-thread Cloak", type="Cloak", skill=21},
  {id=4714, name="Silver-thread Sash", type="Cloth Armor", skill=22},
  {id=4734, name="Mistscape Mantle", type="Cloth Armor", skill=38},
  {id=4735, name="Mistscape Cloak", type="Cloak", skill=36},
  {id=5002, name="Glowing Green Talisman", type="Amulet", skill=25},
  {id=5003, name="Crystal Starfire Medallion", type="Amulet", skill=26},
  {id=5207, name="Opaque Wand", type="Wand", skill=15},
  {id=5212, name="Blazing Wand", type="Wand", skill=12},
  {id=5213, name="Scorching Wand", type="Wand", skill=30},
  {id=5498, name="Small Lustrous Pearl", type="Trade Good"},
  {id=5500, name="Iridescent Pearl", type="Trade Good"},
  {id=5572, name="Small Green Pouch", type="Bag"},
  {id=5573, name="Green Leather Bag", type="Bag"},
  {id=5574, name="White Leather Bag", type="Bag"},
  {id=5575, name="Large Green Sack", type="Bag"},
  {id=5576, name="Large Brown Sack", type="Bag"},
  {id=6149, name="Greater Mana Potion", type="Potion", skill=31},
  {id=6266, name="Disciple's Vest", type="Cloth Armor", skill=8},
  {id=6268, name="Pioneer Tunic", type="Leather Armor", skill=8},
  {id=6269, name="Pioneer Trousers", type="Leather Armor", skill=7},
  {id=6271, name="Pattern: Red Linen Vest", type="Tailoring Pattern"},
  {id=6289, name="Raw Longjaw Mud Snapper", type="Meat", skill=5},
  {id=6291, name="Raw Brilliant Smallfish", type="Meat", skill=1},
  {id=6292, name="10 Pound Mud Snapper", type="Off-hand Frill"},
  {id=6294, name="12 Pound Mud Snapper", type="Off-hand Frill"},
  {id=6295, name="15 Pound Mud Snapper", type="Off-hand Frill"},
  {id=6297, name="Old Skull", type="Junk"},
  {id=6299, name="Sickly Looking Fish", type="Food or Drink", skill=1},
  {id=6301, name="Old Teamster's Skull", type="Junk"},
  {id=6303, name="Raw Slitherskin Mackerel", type="Meat", skill=1},
  {id=6304, name="Damp Diary Page (Day 4)", type="Junk"},
  {id=6306, name="Damp Diary Page (Day 512)", type="Junk"},
  {id=6307, name="Message in a Bottle", type="Miscellaneous Item"},
  {id=6308, name="Raw Bristle Whisker Catfish", type="Meat", skill=15},
  {id=6309, name="17 Pound Catfish", type="Off-hand Frill"},
  {id=6310, name="19 Pound Catfish", type="Off-hand Frill"},
  {id=6311, name="22 Pound Catfish", type="Off-hand Frill"},
  {id=6317, name="Raw Loch Frenzy", type="Meat", skill=5},
  {id=6336, name="Infantry Tunic", type="Mail Armor", skill=8},
  {id=6348, name="Formula: Enchant Weapon - Minor Beastslayer", type="Enchanting Formula"},
  {id=6351, name="Dented Crate", type="Miscellaneous Item"},
  {id=6352, name="Waterlogged Crate", type="Miscellaneous Item"},
  {id=6353, name="Small Chest", type="Miscellaneous Item"},
  {id=6354, name="Small Locked Chest", type="Miscellaneous Item"},
  {id=6355, name="Sturdy Locked Chest", type="Miscellaneous Item"},
  {id=6356, name="Battered Chest", type="Miscellaneous Item"},
  {id=6357, name="Sealed Crate", type="Miscellaneous Item"},
  {id=6358, name="Oily Blackmouth", type="Trade Good"},
  {id=6359, name="Firefin Snapper", type="Trade Good"},
  {id=6360, name="Steelscale Crushfish", type="One-Handed Mace", skill=20},
  {id=6361, name="Raw Rainbow Fin Albacore", type="Meat", skill=5},
  {id=6362, name="Raw Rockscale Cod", type="Meat", skill=25},
  {id=6363, name="26 Pound Catfish", type="Off-hand Frill"},
  {id=6364, name="32 Pound Catfish", type="Off-hand Frill"},
  {id=6378, name="Seer's Cape", type="Cloak", skill=12},
  {id=6379, name="Inscribed Leather Belt", type="Leather Armor", skill=12},
  {id=6380, name="Inscribed Buckler", type="Shield", skill=13},
  {id=6381, name="Bright Cloak", type="Cloak", skill=18},
  {id=6387, name="Glimmering Mail Bracers", type="Mail Armor", skill=24},
  {id=6388, name="Glimmering Mail Pauldrons", type="Mail Armor", skill=25},
  {id=6389, name="Glimmering Mail Coif", type="Mail Armor", skill=26},
  {id=6391, name="Pattern: Stylish Green Shirt", type="Tailoring Pattern"},
  {id=6394, name="Silver-thread Boots", type="Cloth Armor", skill=22},
  {id=6396, name="Emblazoned Chestpiece", type="Leather Armor", skill=27},
  {id=6398, name="Emblazoned Belt", type="Leather Armor", skill=24},
  {id=6399, name="Emblazoned Shoulders", type="Leather Armor", skill=25},
  {id=6405, name="Nightsky Trousers", type="Cloth Armor", skill=31},
  {id=6409, name="Insignia Belt", type="Leather Armor", skill=29},
  {id=6411, name="Chief Brigadier Armor", type="Mail Armor", skill=36},
  {id=6412, name="Chief Brigadier Boots", type="Mail Armor", skill=34},
  {id=6418, name="Aurora Sash", type="Cloth Armor", skill=32},
  {id=6419, name="Glyphed Mitts", type="Leather Armor", skill=33},
  {id=6421, name="Glyphed Belt", type="Leather Armor", skill=33},
  {id=6429, name="Mistscape Wizard Hat", type="Cloth Armor", skill=39},
  {id=6455, name="Old Wagonwheel", type="Junk"},
  {id=6456, name="Acidic Slime", type="Junk"},
  {id=6457, name="Rusted Engineering Parts", type="Junk"},
  {id=6458, name="Oil Covered Fish", type="Consumable", skill=5},
  {id=6470, name="Deviate Scale", type="Leather"},
  {id=6506, name="Infantry Boots", type="Mail Armor", skill=6},
  {id=6507, name="Infantry Bracers", type="Mail Armor", skill=5},
  {id=6508, name="Infantry Cloak", type="Cloak", skill=4},
  {id=6509, name="Infantry Belt", type="Mail Armor", skill=5},
  {id=6510, name="Infantry Gauntlets", type="Mail Armor", skill=6},
  {id=6512, name="Disciple's Robe", type="Cloth Armor", skill=8},
  {id=6513, name="Disciple's Sash", type="Cloth Armor", skill=5},
  {id=6514, name="Disciple's Cloak", type="Cloak", skill=5},
  {id=6515, name="Disciple's Gloves", type="Cloth Armor", skill=6},
  {id=6517, name="Pioneer Belt", type="Leather Armor", skill=5},
  {id=6518, name="Pioneer Boots", type="Leather Armor", skill=6},
  {id=6520, name="Pioneer Cloak", type="Cloak", skill=4},
  {id=6521, name="Pioneer Gloves", type="Leather Armor", skill=6},
  {id=6522, name="Deviate Fish", type="Food or Drink"},
  {id=6538, name="Willow Robe", type="Cloth Armor", skill=14},
  {id=6539, name="Willow Belt", type="Cloth Armor", skill=11},
  {id=6540, name="Willow Pants", type="Cloth Armor", skill=13},
  {id=6541, name="Willow Gloves", type="Cloth Armor", skill=11},
  {id=6543, name="Willow Bracers", type="Cloth Armor", skill=10},
  {id=6545, name="Soldier's Armor", type="Mail Armor", skill=13},
  {id=6546, name="Soldier's Leggings", type="Mail Armor", skill=12},
  {id=6548, name="Soldier's Girdle", type="Mail Armor", skill=11},
  {id=6549, name="Soldier's Cloak", type="Cloak", skill=9},
  {id=6551, name="Soldier's Boots", type="Mail Armor", skill=12},
  {id=6552, name="Bard's Tunic", type="Leather Armor", skill=14},
  {id=6553, name="Bard's Trousers", type="Leather Armor", skill=13},
  {id=6554, name="Bard's Gloves", type="Leather Armor", skill=12},
  {id=6555, name="Bard's Cloak", type="Cloak", skill=9},
  {id=6556, name="Bard's Bracers", type="Leather Armor", skill=10},
  {id=6557, name="Bard's Boots", type="Leather Armor", skill=11},
  {id=6558, name="Bard's Belt", type="Leather Armor", skill=10},
  {id=6559, name="Bard's Buckler", type="Shield", skill=11},
  {id=6560, name="Soldier's Shield", type="Shield", skill=12},
  {id=6561, name="Seer's Padded Armor", type="Cloth Armor", skill=16},
  {id=6562, name="Shimmering Boots", type="Cloth Armor", skill=16},
  {id=6563, name="Shimmering Bracers", type="Cloth Armor", skill=15},
  {id=6564, name="Shimmering Cloak", type="Cloak", skill=16},
  {id=6566, name="Shimmering Amice", type="Cloth Armor", skill=19},
  {id=6567, name="Shimmering Armor", type="Cloth Armor", skill=20},
  {id=6568, name="Shimmering Trousers", type="Cloth Armor", skill=19},
  {id=6569, name="Shimmering Robe", type="Cloth Armor", skill=20},
  {id=6571, name="Scouting Buckler", type="Shield", skill=17},
  {id=6572, name="Defender Shield", type="Shield", skill=18},
  {id=6574, name="Defender Bracers", type="Mail Armor", skill=17},
  {id=6576, name="Defender Girdle", type="Mail Armor", skill=17},
  {id=6578, name="Defender Leggings", type="Mail Armor", skill=18},
  {id=6580, name="Defender Tunic", type="Mail Armor", skill=18},
  {id=6583, name="Scouting Bracers", type="Leather Armor", skill=16},
  {id=6584, name="Scouting Tunic", type="Leather Armor", skill=20},
  {id=6585, name="Scouting Cloak", type="Cloak", skill=15},
  {id=6587, name="Scouting Trousers", type="Leather Armor", skill=19},
  {id=6592, name="Battleforge Armor", type="Mail Armor", skill=24},
  {id=6595, name="Battleforge Gauntlets", type="Mail Armor", skill=23},
  {id=6596, name="Battleforge Legguards", type="Mail Armor", skill=23},
  {id=6597, name="Battleforge Shoulderguards", type="Mail Armor", skill=23},
  {id=6600, name="Dervish Belt", type="Leather Armor", skill=22},
  {id=6601, name="Dervish Boots", type="Leather Armor", skill=23},
  {id=6603, name="Dervish Tunic", type="Leather Armor", skill=25},
  {id=6604, name="Dervish Cape", type="Cloak", skill=21},
  {id=6605, name="Dervish Gloves", type="Leather Armor", skill=23},
  {id=6611, name="Sage's Sash", type="Cloth Armor", skill=24},
  {id=6612, name="Sage's Boots", type="Cloth Armor", skill=23},
  {id=6614, name="Sage's Cloak", type="Cloak", skill=23},
  {id=6615, name="Sage's Gloves", type="Cloth Armor", skill=24},
  {id=6643, name="Bloated Brilliant Smallfish", type="Miscellaneous Item"},
  {id=6645, name="Bloated Mud Snapper", type="Miscellaneous Item"},
  {id=6647, name="Bloated Bristle Whisker Catfish", type="Miscellaneous Item"},
  {id=6717, name="Gaffer Jack", type="Quest"},
  {id=6718, name="Electropeller", type="Quest"},
  {id=7070, name="Elemental Water", type="Elemental"},
  {id=7079, name="Globe of Water", type="Elemental"},
  {id=7080, name="Essence of Water", type="Elemental"},
  {id=7085, name="Pattern: Azure Shoulders", type="Tailoring Pattern"},
  {id=7092, name="Pattern: Hands of Darkness", type="Tailoring Pattern"},
  {id=7108, name="Infantry Shield", type="Shield", skill=6},
  {id=7109, name="Pioneer Buckler", type="Shield", skill=4},
  {id=7112, name="Aurora Armor", type="Cloth Armor", skill=36},
  {id=7288, name="Pattern: Rugged Leather Pants", type="Leatherworking Pattern"},
  {id=7350, name="Disciple's Bracers", type="Cloth Armor", skill=5},
  {id=7351, name="Disciple's Boots", type="Cloth Armor", skill=6},
  {id=7354, name="Elder's Boots", type="Cloth Armor", skill=28},
  {id=7356, name="Elder's Cloak", type="Cloak", skill=25},
  {id=7370, name="Elder's Sash", type="Cloth Armor", skill=26},
  {id=7410, name="Infiltrator Bracers", type="Leather Armor", skill=26},
  {id=7412, name="Infiltrator Gloves", type="Leather Armor", skill=27},
  {id=7415, name="Dervish Spaulders", type="Leather Armor", skill=24},
  {id=7416, name="Phalanx Bracers", type="Mail Armor", skill=26},
  {id=7424, name="Phalanx Spaulders", type="Mail Armor", skill=28},
  {id=7440, name="Sentinel Trousers", type="Leather Armor", skill=34},
  {id=7443, name="Sentinel Gloves", type="Leather Armor", skill=32},
  {id=7448, name="Sentinel Girdle", type="Leather Armor", skill=31},
  {id=7455, name="Knight's Legguards", type="Mail Armor", skill=34},
  {id=7477, name="Ranger Tunic", type="Leather Armor", skill=40},
  {id=7479, name="Ranger Helm", type="Leather Armor", skill=37},
  {id=7485, name="Ranger Cord", type="Leather Armor", skill=36},
  {id=7486, name="Captain's Breastplate", type="Mail Armor", skill=39},
  {id=7496, name="Field Plate Shield", type="Shield", skill=38},
  {id=7517, name="Gossamer Tunic", type="Cloth Armor", skill=45},
  {id=7521, name="Gossamer Gloves", type="Cloth Armor", skill=41},
  {id=7523, name="Gossamer Shoulderpads", type="Cloth Armor", skill=41},
  {id=7525, name="Gossamer Bracers", type="Cloth Armor", skill=40},
  {id=7526, name="Gossamer Belt", type="Cloth Armor", skill=41},
  {id=7528, name="Cabalist Leggings", type="Leather Armor", skill=43},
  {id=7530, name="Cabalist Gloves", type="Leather Armor", skill=41},
  {id=7536, name="Champion's Wall Shield", type="Shield", skill=43},
  {id=7545, name="Champion's Bracers", type="Mail Armor", skill=40},
  {id=7558, name="Shimmering Stave", type="Off-hand Frill", skill=20},
  {id=7909, name="Aquamarine", type="Trade Good"},
  {id=7910, name="Star Ruby", type="Trade Good"},
  {id=7971, name="Black Pearl", type="Trade Good"},
  {id=7973, name="Big-mouth Clam", type="Trade Good"},
  {id=7974, name="Zesty Clam Meat", type="Meat"},
  {id=7975, name="Plans: Heavy Mithril Pants", type="Blacksmithing Plans"},
  {id=7990, name="Plans: Heavy Mithril Helm", type="Blacksmithing Plans"},
  {id=7992, name="Plans: Blue Glittering Axe", type="Blacksmithing Plans"},
  {id=8108, name="Hibernal Bracers", type="Cloth Armor", skill=42},
  {id=8118, name="Heraldic Bracers", type="Leather Armor", skill=41},
  {id=8120, name="Heraldic Cloak", type="Cloak", skill=40},
  {id=8125, name="Myrmidon's Bracers", type="Mail Armor", skill=43},
  {id=8126, name="Myrmidon's Breastplate", type="Mail Armor", skill=46},
  {id=8138, name="Chromite Chestplate", type="Plate Armor", skill=42},
  {id=8159, name="Jouster's Girdle", type="Plate Armor", skill=40},
  {id=8160, name="Jouster's Greaves", type="Plate Armor", skill=40},
  {id=8170, name="Rugged Leather", type="Leather"},
  {id=8177, name="Practice Sword", type="Two-Handed Sword", skill=2},
  {id=8178, name="Training Sword", type="Two-Handed Sword", skill=5},
  {id=8179, name="Cadet's Bow", type="Bow", skill=1},
  {id=8180, name="Hunting Bow", type="Bow", skill=6},
  {id=8181, name="Hunting Rifle", type="Gun", skill=4},
  {id=8182, name="Pellet Rifle", type="Gun", skill=2},
  {id=8183, name="Precision Bow", type="Bow", skill=22},
  {id=8184, name="Firestarter", type="Wand", skill=24},
  {id=8186, name="Dire Wand", type="Wand", skill=21},
  {id=8196, name="Ebon Scimitar", type="One-Handed Sword", skill=38},
  {id=8199, name="Battlefield Destroyer", type="Two-Handed Sword", skill=42},
  {id=8256, name="Serpentskin Boots", type="Leather Armor", skill=47},
  {id=8259, name="Serpentskin Cloak", type="Cloak", skill=45},
  {id=8267, name="Ebonhold Gauntlets", type="Mail Armor", skill=49},
  {id=8273, name="Valorous Wristguards", type="Plate Armor", skill=41},
  {id=8305, name="Hero's Gauntlets", type="Mail Armor", skill=54},
  {id=8306, name="Hero's Belt", type="Mail Armor", skill=54},
  {id=8314, name="Alabaster Plate Gauntlets", type="Plate Armor", skill=48},
  {id=8317, name="Alabaster Plate Helmet", type="Plate Armor", skill=49},
  {id=8350, name="The 1 Ring", type="Ring", skill=10},
  {id=8365, name="Raw Mithril Head Trout", type="Meat", skill=25},
  {id=8366, name="Bloated Mithril Head Trout", type="Miscellaneous Item"},
  {id=8385, name="Pattern: Turtle Scale Gloves", type="Leatherworking Pattern"},
  {id=9291, name="Field Plate Leggings", type="Plate Armor", skill=40},
  {id=9295, name="Recipe: Invisibility Potion", type="Alchemy Recipe"},
  {id=9744, name="Simple Bands", type="Cloth Armor", skill=7},
  {id=9745, name="Simple Cape", type="Cloak", skill=6},
  {id=9746, name="Simple Gloves", type="Cloth Armor", skill=8},
  {id=9749, name="Simple Blouse", type="Cloth Armor", skill=10},
  {id=9750, name="Nomad Sash", type="Leather Armor", skill=7},
  {id=9751, name="Nomad Sandals", type="Leather Armor", skill=7},
  {id=9752, name="Nomad Bands", type="Leather Armor", skill=7},
  {id=9753, name="Nomad Buckler", type="Shield", skill=7},
  {id=9754, name="Nomad Cloak", type="Cloak", skill=6},
  {id=9755, name="Nomad Gloves", type="Leather Armor", skill=8},
  {id=9756, name="Nomad Trousers", type="Leather Armor", skill=9},
  {id=9757, name="Nomad Tunic", type="Leather Armor", skill=10},
  {id=9761, name="Cadet Cloak", type="Cloak", skill=6},
  {id=9762, name="Cadet Gauntlets", type="Mail Armor", skill=8},
  {id=9763, name="Cadet Leggings", type="Mail Armor", skill=9},
  {id=9765, name="Cadet Vest", type="Mail Armor", skill=10},
  {id=9775, name="Bandit Cinch", type="Leather Armor", skill=14},
  {id=9776, name="Bandit Boots", type="Leather Armor", skill=15},
  {id=9777, name="Bandit Bracers", type="Leather Armor", skill=14},
  {id=9779, name="Bandit Cloak", type="Cloak", skill=13},
  {id=9781, name="Bandit Pants", type="Leather Armor", skill=17},
  {id=9783, name="Raider's Chestpiece", type="Mail Armor", skill=15},
  {id=9784, name="Raider's Boots", type="Mail Armor", skill=14},
  {id=9785, name="Raider's Bracers", type="Mail Armor", skill=12},
  {id=9786, name="Raider's Cloak", type="Cloak", skill=11},
  {id=9787, name="Raider's Gauntlets", type="Mail Armor", skill=14},
  {id=9788, name="Raider's Belt", type="Mail Armor", skill=13},
  {id=9789, name="Raider's Legguards", type="Mail Armor", skill=14},
  {id=9795, name="Ivycloth Gloves", type="Cloth Armor", skill=21},
  {id=9797, name="Ivycloth Pants", type="Cloth Armor", skill=23},
  {id=9798, name="Ivycloth Robe", type="Cloth Armor", skill=24},
  {id=9799, name="Ivycloth Sash", type="Cloth Armor", skill=21},
  {id=9800, name="Ivy Orb", type="Off-hand Frill", skill=24},
  {id=9807, name="Superior Shoulders", type="Leather Armor", skill=22},
  {id=9811, name="Fortified Bracers", type="Mail Armor", skill=19},
  {id=9814, name="Fortified Belt", type="Mail Armor", skill=19},
  {id=9815, name="Fortified Leggings", type="Mail Armor", skill=20},
  {id=9816, name="Fortified Shield", type="Shield", skill=20},
  {id=9817, name="Fortified Spaulders", type="Mail Armor", skill=21},
  {id=9818, name="Fortified Chain", type="Mail Armor", skill=20},
  {id=9826, name="Durable Robe", type="Cloth Armor", skill=29},
  {id=9837, name="Banded Bracers", type="Mail Armor", skill=25},
  {id=9840, name="Banded Girdle", type="Mail Armor", skill=26},
  {id=9845, name="Conjurer's Shoes", type="Cloth Armor", skill=30},
  {id=9851, name="Conjurer's Breeches", type="Cloth Armor", skill=32},
  {id=9857, name="Archer's Bracers", type="Leather Armor", skill=29},
  {id=9858, name="Archer's Buckler", type="Shield", skill=31},
  {id=9861, name="Archer's Gloves", type="Leather Armor", skill=30},
  {id=9862, name="Archer's Trousers", type="Leather Armor", skill=32},
  {id=9863, name="Archer's Shoulderpads", type="Leather Armor", skill=32},
  {id=9866, name="Renegade Chestguard", type="Mail Armor", skill=33},
  {id=9870, name="Renegade Circlet", type="Mail Armor", skill=31},
  {id=9876, name="Sorcerer Slippers", type="Cloth Armor", skill=35},
  {id=9878, name="Sorcerer Hat", type="Cloth Armor", skill=36},
  {id=9879, name="Sorcerer Bracelets", type="Cloth Armor", skill=34},
  {id=9880, name="Sorcerer Gloves", type="Cloth Armor", skill=35},
  {id=9885, name="Huntsman's Boots", type="Leather Armor", skill=35},
  {id=9886, name="Huntsman's Bands", type="Leather Armor", skill=34},
  {id=9890, name="Huntsman's Cape", type="Cloak", skill=33},
  {id=9894, name="Huntsman's Shoulders", type="Leather Armor", skill=36},
  {id=9898, name="Jazeraint Cloak", type="Cloak", skill=33},
  {id=9906, name="Royal Sash", type="Cloth Armor", skill=39},
  {id=9909, name="Royal Bands", type="Cloth Armor", skill=38},
  {id=9910, name="Royal Gloves", type="Cloth Armor", skill=39},
  {id=9912, name="Royal Amice", type="Cloth Armor", skill=40},
  {id=9916, name="Tracker's Belt", type="Leather Armor", skill=39},
  {id=9919, name="Tracker's Cloak", type="Cloak", skill=38},
  {id=9923, name="Tracker's Shoulderpads", type="Leather Armor", skill=40},
  {id=9931, name="Brigade Girdle", type="Mail Armor", skill=38},
  {id=9934, name="Brigade Pauldrons", type="Mail Armor", skill=39},
  {id=9942, name="Abjurer's Pants", type="Cloth Armor", skill=45},
  {id=9946, name="Abjurer's Tunic", type="Cloth Armor", skill=48},
  {id=9949, name="Chieftain's Bracers", type="Leather Armor", skill=43},
  {id=9950, name="Chieftain's Breastplate", type="Leather Armor", skill=48},
  {id=9951, name="Chieftain's Cloak", type="Cloak", skill=42},
  {id=9953, name="Chieftain's Headdress", type="Leather Armor", skill=45},
  {id=9961, name="Warmonger's Belt", type="Mail Armor", skill=42},
  {id=9963, name="Warmonger's Circlet", type="Mail Armor", skill=43},
  {id=9973, name="Embossed Plate Boots", type="Plate Armor", skill=40},
  {id=9974, name="Overlord's Shield", type="Shield", skill=47},
  {id=10059, name="Duskwoven Bracers", type="Cloth Armor", skill=45},
  {id=10063, name="Duskwoven Amice", type="Cloth Armor", skill=46},
  {id=10074, name="Righteous Leggings", type="Leather Armor", skill=48},
  {id=10077, name="Lord's Breastplate", type="Mail Armor", skill=48},
  {id=10082, name="Lord's Boots", type="Mail Armor", skill=46},
  {id=10089, name="Gothic Sabatons", type="Plate Armor", skill=40},
  {id=10091, name="Gothic Plate Leggings", type="Plate Armor", skill=42},
  {id=10092, name="Gothic Plate Spaulders", type="Plate Armor", skill=42},
  {id=10096, name="Councillor's Cuffs", type="Cloth Armor", skill=49},
  {id=10100, name="Councillor's Shoulders", type="Cloth Armor", skill=52},
  {id=10108, name="Wanderer's Cloak", type="Cloak", skill=48},
  {id=10124, name="Ornate Legguards", type="Mail Armor", skill=52},
  {id=10130, name="Revenant Girdle", type="Plate Armor", skill=45},
  {id=10148, name="Mighty Cloak", type="Cloak", skill=53},
  {id=10164, name="Templar Chestplate", type="Plate Armor", skill=53},
  {id=10168, name="Templar Crown", type="Plate Armor", skill=51},
  {id=10172, name="Mystical Mantle", type="Cloth Armor", skill=50},
  {id=10186, name="Swashbuckler's Gloves", type="Leather Armor", skill=48},
  {id=10197, name="Crusader's Belt", type="Mail Armor", skill=47},
  {id=10199, name="Crusader's Leggings", type="Mail Armor", skill=49},
  {id=10224, name="Nightshade Cloak", type="Cloak", skill=52},
  {id=10234, name="Engraved Boots", type="Mail Armor", skill=53},
  {id=10242, name="Heavy Lamellar Gauntlets", type="Plate Armor", skill=47},
  {id=10244, name="Heavy Lamellar Leggings", type="Plate Armor", skill=49},
  {id=10280, name="Emerald Legplates", type="Plate Armor", skill=54},
  {id=10282, name="Emerald Vambraces", type="Plate Armor", skill=51},
  {id=10300, name="Pattern: Red Mageweave Vest", type="Tailoring Pattern"},
  {id=10312, name="Pattern: Red Mageweave Gloves", type="Tailoring Pattern"},
  {id=10320, name="Pattern: Red Mageweave Headband", type="Tailoring Pattern"},
  {id=10374, name="Imbued Plate Pauldrons", type="Plate Armor", skill=54},
  {id=10404, name="Durable Belt", type="Cloth Armor", skill=25},
  {id=10406, name="Scaled Leather Headband", type="Leather Armor", skill=27},
  {id=10409, name="Banded Boots", type="Mail Armor", skill=27},
  {id=10424, name="Plans: Silvered Bronze Leggings", type="Blacksmithing Plans"},
  {id=10505, name="Solid Blasting Powder", type="Part"},
  {id=10561, name="Mithril Casing", type="Part"},
  {id=10601, name="Schematic: Bright-Eye Goggles", type="Engineering Schematic", skill=5},
  {id=11081, name="Formula: Enchant Shield - Lesser Protection", type="Enchanting Formula"},
  {id=11098, name="Formula: Enchant Cloak - Lesser Shadow Resistance", type="Enchanting Formula"},
  {id=11165, name="Formula: Enchant Weapon - Lesser Elemental Slayer", type="Enchanting Formula"},
  {id=11167, name="Formula: Enchant Boots - Lesser Spirit", type="Enchanting Formula"},
  {id=11202, name="Formula: Enchant Shield - Stamina", type="Enchanting Formula"},
  {id=11204, name="Formula: Enchant Bracer - Greater Spirit", type="Enchanting Formula"},
  {id=11225, name="Formula: Enchant Bracer - Greater Stamina", type="Enchanting Formula"},
  {id=11967, name="Zircon Band", type="Ring", skill=18},
  {id=11970, name="Spinel Ring", type="Ring", skill=29},
  {id=11972, name="Carnelian Loop", type="Ring", skill=35},
  {id=11976, name="Sardonyx Knuckle", type="Ring", skill=47},
  {id=11982, name="Viridian Band", type="Ring", skill=18},
  {id=11996, name="Basalt Ring", type="Ring", skill=29},
  {id=12007, name="Prairie Ring", type="Ring", skill=20},
  {id=12008, name="Savannah Ring", type="Ring", skill=23},
  {id=12010, name="Fen Ring", type="Ring", skill=32},
  {id=12026, name="Quicksilver Pendant", type="Amulet", skill=54},
  {id=12029, name="Greenstone Talisman", type="Amulet", skill=30},
  {id=12047, name="Spectral Necklace", type="Amulet", skill=25},
  {id=12238, name="Darkshore Grouper", type="Food or Drink", skill=5},
  {id=13422, name="Stonescale Eel", type="Trade Good"},
  {id=13443, name="Superior Mana Potion", type="Potion", skill=41},
  {id=13446, name="Major Healing Potion", type="Potion", skill=45},
  {id=13754, name="Raw Glossy Mightfish", type="Meat", skill=35},
  {id=13755, name="Raw Winter Squid", type="Food or Drink", skill=35},
  {id=13756, name="Raw Summer Bass", type="Meat", skill=35},
  {id=13757, name="Lightning Eel", type="Trade Good"},
  {id=13758, name="Raw Redgill", type="Meat", skill=35},
  {id=13759, name="Raw Nightfin Snapper", type="Meat", skill=35},
  {id=13760, name="Raw Sunscale Salmon", type="Meat", skill=35},
  {id=13874, name="Heavy Crate", type="Miscellaneous Item"},
  {id=13875, name="Ironbound Locked Chest", type="Miscellaneous Item"},
  {id=13876, name="40 Pound Yellowtail", type="Miscellaneous Item"},
  {id=13877, name="47 Pound Yellowtail", type="Miscellaneous Item"},
  {id=13878, name="53 Pound Yellowtail", type="Miscellaneous Item"},
  {id=13879, name="59 Pound Yellowtail", type="Miscellaneous Item"},
  {id=13880, name="68 Pound Yellowtail", type="Miscellaneous Item"},
  {id=13881, name="Bloated Redgill", type="Miscellaneous Item"},
  {id=13882, name="42 Pound Redgill", type="Off-hand Frill"},
  {id=13883, name="45 Pound Redgill", type="Off-hand Frill"},
  {id=13884, name="49 Pound Redgill", type="Off-hand Frill"},
  {id=13885, name="34 Pound Redgill", type="Off-hand Frill"},
  {id=13886, name="37 Pound Redgill", type="Off-hand Frill"},
  {id=13887, name="52 Pound Redgill", type="Off-hand Frill"},
  {id=13888, name="Darkclaw Lobster", type="Meat", skill=45},
  {id=13889, name="Raw Whitescale Salmon", type="Meat", skill=45},
  {id=13890, name="Raw Plated Armorfish", type="Quest"},
  {id=13891, name="Bloated Whitescale Salmon", type="Miscellaneous Item"},
  {id=13893, name="Large Raw Mightfish", type="Food or Drink", skill=45},
  {id=13901, name="15 Pound Salmon", type="Off-hand Frill"},
  {id=13902, name="18 Pound Salmon", type="Off-hand Frill"},
  {id=13903, name="22 Pound Salmon", type="Off-hand Frill"},
  {id=13904, name="25 Pound Salmon", type="Off-hand Frill"},
  {id=13905, name="29 Pound Salmon", type="Off-hand Frill"},
  {id=13907, name="7 Pound Lobster", type="Miscellaneous Item"},
  {id=13908, name="9 Pound Lobster", type="Miscellaneous Item"},
  {id=13909, name="12 Pound Lobster", type="Miscellaneous Item"},
  {id=13910, name="15 Pound Lobster", type="Miscellaneous Item"},
  {id=13911, name="19 Pound Lobster", type="Miscellaneous Item"},
  {id=13912, name="21 Pound Lobster", type="Miscellaneous Item"},
  {id=13913, name="22 Pound Lobster", type="Miscellaneous Item", skill=1},
  {id=13914, name="70 Pound Mightfish", type="Off-hand Frill"},
  {id=13915, name="85 Pound Mightfish", type="Off-hand Frill"},
  {id=13916, name="92 Pound Mightfish", type="Off-hand Frill"},
  {id=13918, name="Reinforced Locked Chest", type="Miscellaneous Item"},
  {id=13926, name="Golden Pearl", type="Trade Good"},
  {id=14048, name="Bolt of Runecloth", type="Cloth"},
  {id=14166, name="Buccaneer's Bracers", type="Cloth Armor", skill=14},
  {id=14167, name="Buccaneer's Cape", type="Cloak", skill=14},
  {id=14168, name="Buccaneer's Gloves", type="Cloth Armor", skill=15},
  {id=14170, name="Buccaneer's Mantle", type="Cloth Armor", skill=17},
  {id=14172, name="Buccaneer's Robes", type="Cloth Armor", skill=18},
  {id=14175, name="Buccaneer's Vest", type="Cloth Armor", skill=18},
  {id=14466, name="Pattern: Frostweave Tunic", type="Tailoring Pattern"},
  {id=14474, name="Pattern: Frostweave Gloves", type="Tailoring Pattern"},
  {id=14478, name="Pattern: Brightcloth Robe", type="Tailoring Pattern"},
  {id=14492, name="Pattern: Felcloth Boots", type="Tailoring Pattern"},
  {id=14508, name="Pattern: Felcloth Shoulders", type="Tailoring Pattern"},
  {id=15210, name="Raider Shortsword", type="One-Handed Sword", skill=11},
  {id=15212, name="Fighter Broadsword", type="One-Handed Sword", skill=22},
  {id=15213, name="Mercenary Blade", type="One-Handed Sword", skill=31},
  {id=15215, name="Furious Falchion", type="One-Handed Sword", skill=40},
  {id=15223, name="Jagged Star", type="One-Handed Mace", skill=19},
  {id=15224, name="Battlesmasher", type="One-Handed Mace", skill=20},
  {id=15225, name="Sequoia Hammer", type="One-Handed Mace", skill=28},
  {id=15226, name="Giant Club", type="One-Handed Mace", skill=32},
  {id=15227, name="Diamond-Tip Bludgeon", type="One-Handed Mace", skill=44},
  {id=15228, name="Smashing Star", type="One-Handed Mace", skill=48},
  {id=15230, name="Ridge Cleaver", type="One-Handed Axe", skill=20},
  {id=15232, name="Hacking Cleaver", type="One-Handed Axe", skill=28},
  {id=15233, name="Savage Axe", type="One-Handed Axe", skill=34},
  {id=15234, name="Greater Scythe", type="One-Handed Axe", skill=35},
  {id=15238, name="Warlord's Axe", type="One-Handed Axe", skill=53},
  {id=15241, name="Battle Knife", type="Dagger", skill=21},
  {id=15242, name="Honed Stiletto", type="Dagger", skill=25},
  {id=15245, name="Vorpal Dagger", type="Dagger", skill=45},
  {id=15248, name="Gleaming Claymore", type="Two-Handed Sword", skill=15},
  {id=15249, name="Polished Zweihander", type="Two-Handed Sword", skill=21},
  {id=15250, name="Glimmering Flamberge", type="Two-Handed Sword", skill=27},
  {id=15253, name="Beheading Blade", type="Two-Handed Sword", skill=47},
  {id=15259, name="Hefty Battlehammer", type="Two-Handed Mace", skill=20},
  {id=15262, name="Greater Maul", type="Two-Handed Mace", skill=41},
  {id=15264, name="Backbreaker", type="Two-Handed Mace", skill=51},
  {id=15268, name="Twin-bladed Axe", type="Two-Handed Axe", skill=11},
  {id=15274, name="Diviner Long Staff", type="Staff", skill=47},
  {id=15281, name="Glowstar Rod", type="Wand", skill=52},
  {id=15284, name="Long Battle Bow", type="Bow", skill=24},
  {id=15285, name="Archer's Longbow", type="Bow", skill=27},
  {id=15294, name="Siege Bow", type="Bow", skill=48},
  {id=15322, name="Smoothbore Gun", type="Gun", skill=34},
  {id=15323, name="Percussion Shotgun", type="Gun", skill=45},
  {id=15324, name="Burnside Rifle", type="Gun", skill=51},
  {id=15743, name="Pattern: Heavy Scorpid Belt", type="Leatherworking Pattern"},
  {id=15745, name="Pattern: Runic Leather Belt", type="Leatherworking Pattern"},
  {id=15746, name="Pattern: Chimeric Leggings", type="Leatherworking Pattern"},
  {id=15895, name="Burnt Buckler", type="Shield", skill=3},
  {id=15926, name="Spellbinder Orb", type="Off-hand Frill", skill=12},
  {id=15928, name="Silver-thread Rod", type="Off-hand Frill", skill=26},
  {id=15932, name="Disciple's Stein", type="Off-hand Frill", skill=7},
  {id=15933, name="Simple Branch", type="Off-hand Frill", skill=10},
  {id=15938, name="Mystical Orb", type="Off-hand Frill", skill=53},
  {id=15939, name="Councillor's Scepter", type="Off-hand Frill", skill=54},
  {id=16218, name="Formula: Enchant Bracer - Superior Spirit", type="Enchanting Formula"},
  {id=16967, name="Feralas Ahi", type="Off-hand Frill"},
  {id=16968, name="Sar'theris Striker", type="Quest"},
  {id=16969, name="Savage Coast Blue Sailfin", type="Quest"},
  {id=16970, name="Misty Reed Mahi Mahi", type="Quest"},
  {id=17057, name="Shiny Fish Scales", type="Reagent"},
  {id=17058, name="Fish Oil", type="Reagent"},
  {id=19803, name="Brownell's Blue Striped Racer", type="Quest"},
  {id=19805, name="Keefer's Angelfish", type="Quest"},
  {id=19806, name="Dezian Queenfish", type="Quest"},
  {id=19807, name="Speckled Tastyfish", type="Miscellaneous Item", skill=1},
  {id=19808, name="Rockhide Strongfish", type="One-Handed Mace", skill=40},
  {id=19975, name="Zulian Mudskunk", type="Quest"},
  {id=20708, name="Tightly Sealed Trunk", type="Miscellaneous Item"},
  {id=20709, name="Rumsey Rum Light", type="Food or Drink", skill=14},
  {id=21071, name="Raw Sagefish", type="Meat", skill=10},
  {id=21113, name="Watertight Trunk", type="Miscellaneous Item"},
  {id=21114, name="Rumsey Rum Dark", type="Food or Drink"},
  {id=21150, name="Iron Bound Trunk", type="Miscellaneous Item"},
  {id=21151, name="Rumsey Rum Black Label", type="Food or Drink"},
  {id=21153, name="Raw Greater Sagefish", type="Meat", skill=30},
  {id=21228, name="Mithril Bound Trunk", type="Miscellaneous Item"},
  {id=209027, name="Crab Treats", type="Consumable", skill=1},
}

-- Order the sections appear in
ns.FISH_SECTION_ORDER = {
  "Fish", "Big fish", "Quest fish and items", "Food, drink and reagents", "Materials",
  "Containers and bags", "Gear", "Recipes and patterns",
  "Potions and scrolls", "Junk", "Other", "Not in your list",
}

-- Name rules, checked first. pattern is a Lua pattern matched against the item name.
ns.FISH_NAME_RULES = {
  { pattern = "^%d+ Pound ", section = "Big fish" },   -- "17 Pound Catfish", "92 Pound Mightfish"
}

-- Single items placed in a section by hand, checked before everything else.
-- Mostly true fish whose type in your CSV is not "Meat", plus Zesty Clam Meat,
-- which is typed "Meat" but is food rather than a fish.
ns.FISH_ITEM_SECTION = {
  [6522] = "Fish",   -- Deviate Fish (Food or Drink)
  [12238] = "Fish",   -- Darkshore Grouper (Food or Drink)
  [13755] = "Fish",   -- Raw Winter Squid (Food or Drink)
  [6299] = "Fish",   -- Sickly Looking Fish (Food or Drink)
  [13893] = "Fish",   -- Large Raw Mightfish (Food or Drink)
  [6358] = "Fish",   -- Oily Blackmouth (Trade Good)
  [6359] = "Fish",   -- Firefin Snapper (Trade Good)
  [13422] = "Fish",   -- Stonescale Eel (Trade Good)
  [13757] = "Fish",   -- Lightning Eel (Trade Good)
  [19807] = "Fish",   -- Speckled Tastyfish (Miscellaneous Item)
  [6458] = "Fish",   -- Oil Covered Fish (Consumable)
  [7974] = "Food, drink and reagents",   -- Zesty Clam Meat (Meat): food, not a fish
}

-- Item type (from your CSV) -> section
ns.FISH_SECTION_OF = {
  ["Meat"] = "Fish",
  ["Food or Drink"] = "Food, drink and reagents", ["Consumable"] = "Food, drink and reagents",
  ["Reagent"] = "Food, drink and reagents",
  ["Quest"] = "Quest fish and items",
  ["Trade Good"] = "Materials", ["Herb"] = "Materials", ["Elemental"] = "Materials",
  ["Metal & Stone"] = "Materials", ["Part"] = "Materials", ["Leather"] = "Materials",
  ["Cloth"] = "Materials",
  ["Miscellaneous Item"] = "Containers and bags", ["Bag"] = "Containers and bags",
  ["Leather Armor"] = "Gear", ["Cloth Armor"] = "Gear", ["Mail Armor"] = "Gear",
  ["Plate Armor"] = "Gear", ["Cloak"] = "Gear", ["Shield"] = "Gear", ["Ring"] = "Gear",
  ["Amulet"] = "Gear", ["Off-hand Frill"] = "Gear",
  ["One-Handed Mace"] = "Gear", ["Two-Handed Mace"] = "Gear",
  ["One-Handed Sword"] = "Gear", ["Two-Handed Sword"] = "Gear",
  ["One-Handed Axe"] = "Gear", ["Two-Handed Axe"] = "Gear",
  ["Dagger"] = "Gear", ["Staff"] = "Gear", ["Wand"] = "Gear", ["Bow"] = "Gear", ["Gun"] = "Gear",
  ["Tailoring Pattern"] = "Recipes and patterns", ["Leatherworking Pattern"] = "Recipes and patterns",
  ["Blacksmithing Plans"] = "Recipes and patterns", ["Enchanting Formula"] = "Recipes and patterns",
  ["Alchemy Recipe"] = "Recipes and patterns", ["Engineering Schematic"] = "Recipes and patterns",
  ["Potion"] = "Potions and scrolls", ["Scroll"] = "Potions and scrolls",
  ["Junk"] = "Junk",
}

-- STARS: how many catches (all zones added together) earn each star, by
-- section. A section not listed here uses ns.FISH_STAR_DEFAULT: one star,
-- earned on the first catch. Change the numbers to retune.
ns.FISH_STAR_TIERS = {
  ["Fish"]     = { 5, 25, 50 },   -- 5 catches = 1 star, 25 = 2 stars, 50 = 3 stars
  ["Big fish"] = { 1, 2, 5 },     -- 1 catch  = 1 star, 2 = 2 stars,  5 = 3 stars (they are rare)
}
ns.FISH_STAR_DEFAULT = { 1 }           -- everything else: 1 star for fishing it up